spring:
  application:
    name: spring security 01
  security:
    user:
      name: user
      password: user123
      roles: USER
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
server:
  port: 8080
